# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f78741fcfa1b002dd663ab80d89e1026614b0d37ce6eb387fa2e78e7a4e80b08c0a043dc988b19afa058d73471babb11537a477c1a63df2c06c52f25ab2685c

test:
  secret_key_base: a2bc818d46354ffc87e50e1bac3a5a7d7da8eb094993e82c290adaa84d2479e186f146edf276b5627366cd91108385dba566894cd88f44a67f240dce5105b71b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
